# pyproject.toml
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Doctor_Patient_Record_RestAPI"
version = "0.1"
dependencies = [
    "Django>=3.0","Djangorestframework",
    # Add other dependencies here
]
