# Generated by Django 5.1 on 2024-08-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=50)),
                ('Diagnostics', models.CharField(max_length=250)),
                ('Location', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=100)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PD.department')),
            ],
        ),
        migrations.CreateModel(
            name='Petient_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PetitentID', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('Created_date', models.DateField(auto_now_add=True)),
                ('Diagnostics', models.CharField(max_length=50)),
                ('Observations', models.CharField(max_length=255)),
                ('misc', models.CharField(blank=True, max_length=255)),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PD.department')),
                ('DoctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PD.doctors')),
            ],
        ),
    ]
