# Generated by Django 5.1 on 2024-08-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petient_record',
            name='name',
            field=models.CharField(default='Petient', max_length=100),
        ),
    ]
