# Generated by Django 5.1 on 2024-08-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PD', '0002_alter_petient_record_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='petient_record',
            name='age',
            field=models.IntegerField(default=18, max_length=20),
        ),
    ]
