# Generated by Django 5.1 on 2024-08-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PD', '0003_petient_record_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petient_record',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
