# Generated by Django 5.1 on 2024-08-11 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PD', '0004_alter_petient_record_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctors', to='PD.department'),
        ),
    ]
