# Generated by Django 5.1 on 2024-08-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PD', '0005_alter_doctors_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='Department',
            new_name='department',
        ),
    ]
